using Domain.Entities;
using System.Collections.Generic;

namespace Infrastructure.Seeds
{
    public static class CountrySeed
    {
        public static IList<Country> GetCountries()
        {
            return new List<Country>
            {
                new Country(1, "Australia"),
                new Country(2, "Austria"),
                new Country(3, "Azerbaiyán"),
                new Country(4, "Anguilla"),
                new Country(5, "Argentina"),
                new Country(6, "Armenia"),
                new Country(7, "Bielorrusia"),
                new Country(8, "Belice"),
                new Country(9, "Bélgica"),
                new Country(10, "Bermudas"),
                new Country(11, "Bulgaria"),
                new Country(12, "Brasil"),
                new Country(13, "Reino Unido"),
                new Country(14, "Hungría"),
                new Country(15, "Vietnam"),
                new Country(16, "Haiti"),
                new Country(17, "Guadalupe"),
                new Country(18, "Alemania"),
                new Country(19, "Países Bajos, Holanda"),
                new Country(20, "Grecia"),
                new Country(21, "Georgia"),
                new Country(22, "Dinamarca"),
                new Country(23, "Egipto"),
                new Country(24, "Israel"),
                new Country(25, "India"),
                new Country(26, "Irán"),
                new Country(27, "Irlanda"),
                new Country(28, "España"),
                new Country(29, "Italia"),
                new Country(30, "Kazajstán"),
                new Country(31, "Camerún"),
                new Country(32, "Canadá"),
                new Country(33, "Chipre"),
                new Country(34, "Kirguistán"),
                new Country(35, "China"),
                new Country(36, "Costa Rica"),
                new Country(37, "Kuwait"),
                new Country(38, "Letonia"),
                new Country(39, "Libia"),
                new Country(40, "Lituania"),
                new Country(41, "Luxemburgo"),
                new Country(42, "México"),
                new Country(43, "Moldavia"),
                new Country(44, "Mónaco"),
                new Country(45, "Nueva Zelanda"),
                new Country(46, "Noruega"),
                new Country(47, "Polonia"),
                new Country(48, "Portugal"),
                new Country(49, "Reunión"),
                new Country(50, "Rusia"),
                new Country(51, "El Salvador"),
                new Country(52, "Eslovaquia"),
                new Country(53, "Eslovenia"),
                new Country(54, "Surinam"),
                new Country(55, "Estados Unidos"),
                new Country(56, "Tadjikistan"),
                new Country(57, "Turkmenistan"),
                new Country(58, "Islas Turcas y Caicos"),
                new Country(59, "Turquía"),
                new Country(60, "Uganda"),
                new Country(61, "Uzbekistán"),
                new Country(62, "Ucrania"),
                new Country(63, "Finlandia"),
                new Country(64, "Francia"),
                new Country(65, "República Checa"),
                new Country(66, "Suiza"),
                new Country(67, "Suecia"),
                new Country(68, "Estonia"),
                new Country(69, "Corea del Sur"),
                new Country(70, "Japón"),
                new Country(71, "Croacia"),
                new Country(72, "Rumanía"),
                new Country(73, "Hong Kong"),
                new Country(74, "Indonesia"),
                new Country(75, "Jordania"),
                new Country(76, "Malasia"),
                new Country(77, "Singapur"),
                new Country(78, "Taiwan"),
                new Country(79, "Bosnia y Herzegovina"),
                new Country(80, "Bahamas"),
                new Country(81, "Chile"),
                new Country(82, "Colombia"),
                new Country(83, "Islandia"),
                new Country(84, "Corea del Norte"),
                new Country(85, "Macedonia"),
                new Country(86, "Malta"),
                new Country(87, "Pakistán"),
                new Country(88, "Papúa-Nueva Guinea"),
                new Country(89, "Perú"),
                new Country(90, "Filipinas"),
                new Country(91, "Arabia Saudita"),
                new Country(92, "Tailandia"),
                new Country(93, "Emiratos árabes Unidos"),
                new Country(94, "Groenlandia"),
                new Country(95, "Venezuela"),
                new Country(96, "Zimbabwe"),
                new Country(97, "Kenia"),
                new Country(98, "Algeria"),
                new Country(99, "Líbano"),
                new Country(100, "Botsuana"),
                new Country(101, "Tanzania"),
                new Country(102, "Namibia"),
                new Country(103, "Ecuador"),
                new Country(104, "Marruecos"),
                new Country(105, "Ghana"),
                new Country(106, "Siria"),
                new Country(107, "Nepal"),
                new Country(108, "Mauritania"),
                new Country(109, "Seychelles"),
                new Country(110, "Paraguay"),
                new Country(111, "Uruguay"),
                new Country(112, "Congo (Brazzaville)"),
                new Country(113, "Cuba"),
                new Country(114, "Albania"),
                new Country(115, "Nigeria"),
                new Country(116, "Zambia"),
                new Country(117, "Mozambique"),
                new Country(119, "Angola"),
                new Country(120, "Sri Lanka"),
                new Country(121, "Etiopía"),
                new Country(122, "Túnez"),
                new Country(123, "Bolivia"),
                new Country(124, "Panamá"),
                new Country(125, "Malawi"),
                new Country(126, "Liechtenstein"),
                new Country(127, "Bahrein"),
                new Country(128, "Barbados"),
                new Country(130, "Chad"),
                new Country(131, "Man, Isla de"),
                new Country(132, "Jamaica"),
                new Country(133, "Malí"),
                new Country(134, "Madagascar"),
                new Country(135, "Senegal"),
                new Country(136, "Togo"),
                new Country(137, "Honduras"),
                new Country(138, "República Dominicana"),
                new Country(139, "Mongolia"),
                new Country(140, "Irak"),
                new Country(141, "Sudáfrica"),
                new Country(142, "Aruba"),
                new Country(143, "Gibraltar"),
                new Country(144, "Afganistán"),
                new Country(145, "Andorra"),
                new Country(147, "Antigua y Barbuda"),
                new Country(149, "Bangladesh"),
                new Country(151, "Benín"),
                new Country(152, "Bután"),
                new Country(154, "Islas Virgenes Británicas"),
                new Country(155, "Brunéi"),
                new Country(156, "Burkina Faso"),
                new Country(157, "Burundi"),
                new Country(158, "Camboya"),
                new Country(159, "Cabo Verde"),
                new Country(164, "Comores"),
                new Country(165, "Congo (Kinshasa)"),
                new Country(166, "Cook, Islas"),
                new Country(168, "Costa de Marfil"),
                new Country(169, "Djibouti, Yibuti"),
                new Country(171, "Timor Oriental"),
                new Country(172, "Guinea Ecuatorial"),
                new Country(173, "Eritrea"),
                new Country(175, "Feroe, Islas"),
                new Country(176, "Fiyi"),
                new Country(178, "Polinesia Francesa"),
                new Country(180, "Gabón"),
                new Country(181, "Gambia"),
                new Country(184, "Granada"),
                new Country(185, "Guatemala"),
                new Country(186, "Guernsey"),
                new Country(187, "Guinea"),
                new Country(188, "Guinea-Bissau"),
                new Country(189, "Guyana"),
                new Country(193, "Jersey"),
                new Country(195, "Kiribati"),
                new Country(196, "Laos"),
                new Country(197, "Lesotho"),
                new Country(198, "Liberia"),
                new Country(200, "Maldivas"),
                new Country(201, "Martinica"),
                new Country(202, "Mauricio"),
                new Country(205, "Myanmar"),
                new Country(206, "Nauru"),
                new Country(207, "Antillas Holandesas"),
                new Country(208, "Nueva Caledonia"),
                new Country(209, "Nicaragua"),
                new Country(210, "Níger"),
                new Country(212, "Norfolk Island"),
                new Country(213, "Omán"),
                new Country(215, "Isla Pitcairn"),
                new Country(216, "Qatar"),
                new Country(217, "Ruanda"),
                new Country(218, "Santa Elena"),
                new Country(219, "San Cristobal y Nevis"),
                new Country(220, "Santa Lucía"),
                new Country(221, "San Pedro y Miquelón"),
                new Country(222, "San Vincente y Granadinas"),
                new Country(223, "Samoa"),
                new Country(224, "San Marino"),
                new Country(225, "San Tomé y Príncipe"),
                new Country(226, "Serbia y Montenegro"),
                new Country(227, "Sierra Leona"),
                new Country(228, "Islas Salomón"),
                new Country(229, "Somalia"),
                new Country(232, "Sudán"),
                new Country(234, "Swazilandia"),
                new Country(235, "Tokelau"),
                new Country(236, "Tonga"),
                new Country(237, "Trinidad y Tobago"),
                new Country(239, "Tuvalu"),
                new Country(240, "Vanuatu"),
                new Country(241, "Wallis y Futuna"),
                new Country(242, "Sáhara Occidental"),
                new Country(243, "Yemen"),
                new Country(246, "Puerto Rico")
            };
        }
    }
}
